# Generated by Django 5.0.6 on 2024-07-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_artisanprofile_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.artisanprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services')),
            ],
        ),
    ]
