# Generated by Django 5.0.6 on 2024-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_individual',
            new_name='is_artisan',
        ),
    ]
