# Generated by Django 5.0.6 on 2024-05-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=450)),
                ('longitude', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('business_contact', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[('EL', 'Electrician'), ('PL', 'Plumber'), ('HCL', 'Home Cleaner'), ('INTD', 'Interior Decorator')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
