# Generated by Django 5.0.6 on 2024-05-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_is_individual_user_is_artisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_business',
        ),
    ]
