# Generated by Django 5.0.6 on 2024-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artisanprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='years_of_experience',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 & Above', '4 & Above')], max_length=9, null=True),
        ),
    ]
