# Generated by Django 5.0.6 on 2024-07-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artisanprofile_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='type',
        ),
    ]
