# Generated by Django 5.0.6 on 2024-07-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_artisanprofile_type'),
        ('services', '0003_delete_artisanservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
