# Generated by Django 5.0.6 on 2024-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artisanprofile_service_type'),
        ('services', '0003_delete_artisanservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='service_type',
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='service_type',
            field=models.ManyToManyField(null=True, to='services.services'),
        ),
    ]
