# Generated by Django 5.0.6 on 2024-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_artisanprofile_service_type_and_more'),
        ('services', '0003_delete_artisanservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='service_type',
            field=models.ManyToManyField(to='services.services'),
        ),
    ]
