# Generated by Django 5.0.6 on 2024-07-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_artisanprofile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
    ]
