name: Secure Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SAST Scan
        run: grep -Ri -w '(password|passwd|pass|secret|keys)' .

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./ # Adjust this path if necessary

  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: OWASP ZAP DAST Scan
        continue-on-error: true
        run: |
          docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t 'https://atod-tech.github.io/Backend/' || true
